apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: mcer-core
type: Opaque
stringData:
  private.pem: |
    -----BEGIN PRIVATE KEY-----
    <INSIRA_SUA_CHAVE_PRIVADA_AQUI>
    -----END PRIVATE KEY-----
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    <INSIRA_SUA_CHAVE_PÚBLICA_AQUI>
    -----END PUBLIC KEY-----

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: mcer-core
type: Opaque
stringData:
  jdbc-url: jdbc:postgresql://<DB_HOST>:5432/authdb
  username: your_db_user
  password: your_db_pass