services:
  postgres_authentication:
    container_name: postgres_authentication
    image: postgres:17
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mcer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  server_authentication:
    container_name: server_authentication
    build:
      context: ../authentication
      dockerfile: Dockerfile
    depends_on:
      - postgres_authentication
    env_file:
      - .env-dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
